---
- name: Create rke user with passwordless sudo
  hosts: all
  become: true
  tasks:
    - name: Add docker user
      user:
        name: docker
        shell: /bin/bash


    - name: Create sudo file
      file:
        path: /etc/sudoers.d/docker
        state: touch

    - name: Give rke user passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/docker
        state: present
        line: 'docker ALL=(ALL:ALL) NOPASSWD: ALL'


    - name: Add docker to Docker group
      command: "usermod -aG docker docker"