---
- name: test
  hosts: all
  become: yes
  become_user: docker
  gather_facts: yes

  tasks:


  

  - name: Nginx Bitch!
    community.docker.docker_container:
     name: nginx_Bitch
     image: nginx
     state: started
     restart: yes
     ports:
      - "80:80"
     env:
         SECRET_KEY: "w"
         BOOLEAN_KEY: "yes"

  - name: Elasticsearch Asshole!
    community.docker.docker_container:
     name: elasticsearch_Asshole!
     image: elasticsearch:8.2.2
     state: started
     restart: yes
     ports:
      - "9200:9200"



  


    
