---
- name: test
  hosts: all
  become: yes
  become_user: docker
  gather_facts: yes

  tasks:


  

  - name: Nginx Bitch!
    community.docker.docker_container:
     name: nginx_Bitch
     image: nginx:latest
     state: started
     restart: yes
     ports:
      - "80:80"
     env:
         SECRET_KEY: "{{SECRET_KEY}}"
         BOOLEAN_KEY: "yes"




  


    
