- name: Install docker SDK for python
  hosts: all
  tasks:

   - name: install a dependency (RedHat OS)
     package:
       name: "{{item}}"
       state: present
       update_cache: yes
     loop:
       - python3-pip
     become: yes
     become_user: docker
     become_method: sudo 

   