- name: Install docker SDK for python
  hosts: all
  become: true
  tasks:



   - name: Install python3-pip
     package:
        name: python3-pip
        state: latest

   - name: install pip docker 
     pip:
        name: docker
        executable: pip3
        extra_args: --user docker
     become_user: docker
     
  
     
     
     
   
   

   