- name: install docker
  hosts: all
  
  become: yes
  gather_facts: yes
  tasks:

    ######   Debian key and repo   ######
   
    - name: add GPG key (Debian OS)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: add docker repository to apt (Debian OS)
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_facts['os_family'] == "Debian"

###########   RedHat utils and repo #######

    - name: Add file repo epel
      file: 
        path: /etc/yml.repos.d/epel.repo
        state: touch

    - name: write in file repo epel
      ansible.builtin.blockinfile:
        path: /etc/yml.repos.d/epel.repo
        block: |
          [epel]
          name=Extra Packages for Enterprise Linux 7 - $basearch
          # It is much more secure to use the metalink, but if you wish to use a local mirror
          # place its address here.
          #baseurl=http://download.example/pub/epel/7/$basearch
          metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch&infra=$infra&content=$contentdir
          failovermethod=priority
          enabled=1
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

          [epel-debuginfo]
          name=Extra Packages for Enterprise Linux 7 - $basearch - Debug
          # It is much more secure to use the metalink, but if you wish to use a local mirror
          # place its address here.
          #baseurl=http://download.example/pub/epel/7/$basearch/debug
          metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-debug-7&arch=$basearch&infra=$infra&content=$contentdir
          failovermethod=priority
          enabled=0
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
          gpgcheck=1

          [epel-source]
          name=Extra Packages for Enterprise Linux 7 - $basearch - Source
          # It is much more secure to use the metalink, but if you wish to use a local mirror
          # place it's address here.
          #baseurl=http://download.example/pub/epel/7/source/tree/
          metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-source-7&arch=$basearch&infra=$infra&content=$contentdir
          failovermethod=priority
          enabled=0
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
          gpgcheck=1
      when: ansible_facts['os_family'] == "RedHat" 
      
    - name: install a dependency (RedHat OS)
      package:
        name:
          - yum-utils
        state: present
        update_cache: yes

      when: ansible_facts['os_family'] == "RedHat"

    - name: Add Docker repo (RedHat)
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_facts['os_family'] == "RedHat"

    
###### Start and install docker ############

    - name: install software
      package:
        name:
          - htop
          - vim
          - nmap
        state: present
        update_cache: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Docker start and enable
      systemd:
        name: docker
        state: started
        enabled: true


   
     


      
