- name: Install docker SDK for python
  hosts: all
  become: true
  tasks:



   - name: Install python and python-pip
     package:
        name: "{{item}}"
        state: present
        update_cache: yes
     loop:
        - python
        - python-pip

   - name: install pip docker 
     pip:
        name: docker
        executable: pip2
        extra_args: --user docker
     become_user: docker
     
  
     
     
     
   
   

   