- name: Install docker SDK for python
  hosts: all
  become: yes
  become_user: docker
  tasks:


   - name: check
     shell: whoami
     register: check

   - debug: 
       var: check

   - name: Install pip
     package:
        name: python3-pip
        state: latest
     become: yes
     become_method: sudo
     become_user: docker
   
   

   