- name: Install docker SDK for python
  hosts: all
  
  tasks:

   - name: Install pip
     package:
        name: python3-pip
        state: latest
     become: yes
     become_method: sudo
     become_user: docker
   
   

   