- name: Install docker SDK for python
  hosts: all
  become: true
  tasks:


   - name: Pip install RedHat
     package:
        name: 
           - python2
           - python2-pip
        state: present
     when: ansible_facts['os_family'] == "RedHat"

   - name: Pip install Debian
     package:
        name: 
         - python2
         - python2-pip
        state: present
     when: ansible_facts['os_family'] == "Debian"


   

   - name: install pip docker 
     pip:
        name: docker
        executable: pip2
     vars:
        ansible_python_interpreter: "/usr/bin/python2"
     become_user: docker
     become: true

     
  
     
     
     
   
   

   