- name: Install docker SDK for python
  hosts: all
  become: true
  tasks:


   - name: Pip install RedHat
     package:
        name: 
           - python3
           - python3-pip
        state: present

   - name: install module docker for python
     shell: pip3 install docker --user

  #  - name: install pip docker 
  #    pip:
  #       name: docker
  #       executable: pip3
  #       extra_args: --user
  #    become_user: docker

     
  
     
     
     
   
   

   