- name: Install docker SDK for python
  hosts: all
  become: yes
  become_user: docker
  tasks:

   - name: install a dependency (RedHat OS)
     package:
       name: "{{item}}"
       state: present
       update_cache: yes
     loop:
       - python3-pip

   