- name: Install docker SDK for python
  hosts: all
  become: true
  tasks:



   - name: Install python and python-pip
     package:
        name:
         - python3
         - python3-pip
        state: present
        update_cache: yes

   - name: install pip docker 
     ansible_python_interpreter: /usr/bin/python3
     pip:
        name: docker
        executable: pip3
     become_user: docker
     become: true
     
  
     
     
     
   
   

   